### ISSUE TITLE
GetDirectory - Error getting plugin

### ISSUE THREAD

**Issue by Ommik345** [munselo/plugin.video.dnatv#5]
Hi,

Running Kodi 17.3 and was able to configure dnatv plugin.

Problem is with both Live TV and Recordings with an error as below. Tried changing the service from booxtv to dnatv and back as in another closed issue but no luck.

Not fluent with python but hoping to learn. I doubt script.module.request is the problem though what is it? Is the problem that liveTV and/or recordings is not set - if these are needed where are they set or created?

..
_22:16:27.787 T:1958642608 WARNING: CAddonMgr: 'script.module.requests' required by 'plugin.video.dnatv' is missing. Add-on may not function correctly
22:16:35.266 T:1958642608   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
22:16:43.795 T:1569399792   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'HTTPDigestAuth' object has no attribute 'init_per_thread_state'
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.dnatv/addon.py", line 230, in <module>
                                                main()
                                              File "/home/osmc/.kodi/addons/plugin.video.dnatv/addon.py", line 223, in main
                                                livetv_dir()
                                              File "/home/osmc/.kodi/addons/plugin.video.dnatv/addon.py", line 179, in livetv_dir
                                                dnatv = DNATVSession(username, password, servicename)
                                              File "/home/osmc/.kodi/addons/plugin.video.dnatv/dnatv.py", line 41, in __init__
                                                self.digest_auth.init_per_thread_state()
                                            AttributeError: 'HTTPDigestAuth' object has no attribute 'init_per_thread_state'
                                            -->End of Python script error report<--
22:16:43.949 T:1958642608   ERROR: GetDirectory - Error getting plugin://plugin.video.dnatv/?foldername=liveTV
22:16:43.951 T:1958642608   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.dnatv/?foldername=liveTV) failed
22:16:49.500 T:1569399792   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'HTTPDigestAuth' object has no attribute 'init_per_thread_state'
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.dnatv/addon.py", line 230, in <module>
                                                main()
                                              File "/home/osmc/.kodi/addons/plugin.video.dnatv/addon.py", line 220, in main
                                                recordings_dir()
                                              File "/home/osmc/.kodi/addons/plugin.video.dnatv/addon.py", line 82, in recordings_dir
                                                dnatv = DNATVSession(username, password, servicename)
                                              File "/home/osmc/.kodi/addons/plugin.video.dnatv/dnatv.py", line 41, in __init__
                                                self.digest_auth.init_per_thread_state()
                                            AttributeError: 'HTTPDigestAuth' object has no attribute 'init_per_thread_state'
                                            -->End of Python script error report<--
22:16:49.651 T:1958642608   ERROR: GetDirectory - Error getting plugin://plugin.video.dnatv/?foldername=recordings
22:16:49.653 T:1958642608   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.dnatv/?foldername=recordings) failed_

**Comment by Ommik345** [comment]
Closing this myself - got instructed to install the plugin correctly. Root cause was indeed missing script.module.request. After installing the plugin correctly it started to work.
